# Generated by Django 4.2.7 on 2023-11-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsdb',
            name='difficulty',
            field=models.CharField(choices=[('NA', 'None'), ('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionsdb',
            name='type',
            field=models.CharField(choices=[('None', 'None'), ('multiple', 'multiple'), ('boolean', 'boolean')], default='None', max_length=10),
        ),
    ]
