# Generated by Django 4.2.7 on 2023-11-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionGenerator', '0002_alter_questionsdb_difficulty_alter_questionsdb_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionsDB',
        ),
    ]
