# Generated by Django 4.2.7 on 2023-11-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionGenerator', '0003_delete_questionsdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsDB',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=200)),
                ('correctAns', models.CharField(max_length=100)),
                ('incorrectAns', models.CharField(max_length=500)),
                ('difficulty', models.CharField(choices=[('NA', 'None'), ('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='NA', max_length=10)),
                ('type', models.CharField(choices=[('None', 'None'), ('multiple', 'multiple'), ('boolean', 'boolean')], default='None', max_length=10)),
            ],
        ),
    ]
